service: drone-api

plugins:
  - serverless-dynamodb-local # https://www.npmjs.com/package/serverless-dynamodb-local
  - serverless-offline

custom:
  tableName:
    users: 'users'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      users:
        sources:
          - table: ${self:custom.tableName.users}
            sources: [./seed/users-seed-data.json]

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2
#  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - dynamodb:Query
#        - dynamodb:Scan
#        - dynamodb:GetItem
#        - dynamodb:PutItem
#        - dynamodb:UpdateItem
#        - dynamodb:DeleteItem
#      Resource:
#        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
#  environment:
#    USERS_TABLE: ${self:custom.tableName}

functions:
  - '${file(src/handlers/users/users.serverless.yml)}'

resources:
  Resources:
    usersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName.users}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
